accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'auth'
urlpatterns = [
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('force_logout/<username>', views.user_force_logout, name='force_logout'),
    path('enable/<username>', views.user_enable, name='enable'),
    path('disable/<username>', views.user_disable, name='disable'),
    path('delete/<username>', views.user_delete, name='delete'),
    path('verify/<username>/<token>', views.user_verify_email, name='verify_email'),
    path('gmail/', include('gmailer.urls')),
]

config/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('dashboard/', include('dashboard.urls', namespace='dash')),
    path('auth/', include('accounts.urls', namespace='auth')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.errors.page_not_found'
handler500 = 'core.errors.server_error'
handler403 = 'core.errors.permission_denied'
handler400 = 'core.errors.bad_request'

core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name="home"),
]

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dash'
urlpatterns = [
    path('', views.home, name="home"),
    path('users/', views.users, name='users'),
    path('gmail/', views.gmail, name='gmail'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

dashboard/models.py
from django.db import models

dashboard/forms.py
from accounts.models import User
from django import forms

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'bio', 'birthday', 'picture']
        widgets = {
            'picture': forms.ClearableFileInput(attrs={ 'class': 'form-control mb-3', 'placeholder': 'Profile Picture'}),
        }

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from dashboard.forms import ProfileForm
from accounts.models import User
from accounts.tools import activater


@login_required
def home(request):
    return render(request, 'dashboard/pages/home.html')


@login_required
def profile(request):
    return render(request, 'dashboard/pages/profile.html')


@login_required
@permission_required("is_staff", login_url='/dashboard/')
def users(request):
    users = User.objects.filter(is_staff=False)
    for user in users:
        if not user.email_verified:
            user.hashed = activater.make_token(user)
        else:
            user.hashed = "Verified"
    return render(request, 'dashboard/pages/users.html', {'users': users})


@login_required
@permission_required("is_staff", login_url='/dashboard/')
def gmail(request):
    credentials = None
    # if mailer.activated:
    #     credentials = mailer.credentials
    #     credentials.email = mailer.email
    return render(request, 'dashboard/pages/gmail.html', {'credentials': credentials})


class ProfileEditView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'dashboard/pages/profile_edit.html'
    success_url = '/dashboard/profile'
    form_class = ProfileForm

    def get_object(self, *args, **kwargs):
        return get_object_or_404(User, pk=self.request.user.pk)


profile_edit = ProfileEditView.as_view()

dashboard/templates/dashboard/pages/gmail.html
{% extends "../layouts/base.html" %}
{% load static %}

{% block title %} Gmail {% endblock %}

{% block page_tools %}
  {% if not credentials %}
    <a role="button" class="btn btn-sm btn-outline-success mr-2" href="{% url 'auth:gmail' %}">Activate</a>
  {% else %}
    <a role="button" class="btn btn-sm btn-outline-success mr-2" href="{% url 'auth:gmail_revoke' %}">Deactivate</a>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="mt-5">
    {% if credentials %}
      <p>email: {{ credentials.email }}</p>
      <p>token: {{ credentials.token }}</p>
      <p>refresh_token: {{ credentials.refresh_token }}</p>
      <p>token_uri: {{ credentials.token_uri }}</p>
      <p>client_id: {{ credentials.client_id }}</p>
      <p>client_secret: {{ credentials.client_secret }}</p>
      <p>scopes: {{ credentials.scopes }}</p>
    {% else %}
      Not activated
    {% endif %}
  </div>
{% endblock %}

dashboard/templates/dashboard/pages/home.html
{% extends "../layouts/base.html" %}
{% load static %}

{% block title %} Dashboard {% endblock %}

{% block content %}
<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

<h2>Section title</h2>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        <td>dolor</td>
        <td>sit</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        <td>adipiscing</td>
        <td>elit</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        <td>odio</td>
        <td>Praesent</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>libero</td>
        <td>Sed</td>
        <td>cursus</td>
        <td>ante</td>
      </tr>
      <tr>
        <td>1,004</td>
        <td>dapibus</td>
        <td>diam</td>
        <td>Sed</td>
        <td>nisi</td>
      </tr>
      <tr>
        <td>1,005</td>
        <td>Nulla</td>
        <td>quis</td>
        <td>sem</td>
        <td>at</td>
      </tr>
      <tr>
        <td>1,006</td>
        <td>nibh</td>
        <td>elementum</td>
        <td>imperdiet</td>
        <td>Duis</td>
      </tr>
      <tr>
        <td>1,007</td>
        <td>sagittis</td>
        <td>ipsum</td>
        <td>Praesent</td>
        <td>mauris</td>
      </tr>
      <tr>
        <td>1,008</td>
        <td>Fusce</td>
        <td>nec</td>
        <td>tellus</td>
        <td>sed</td>
      </tr>
      <tr>
        <td>1,009</td>
        <td>augue</td>
        <td>semper</td>
        <td>porta</td>
        <td>Mauris</td>
      </tr>
      <tr>
        <td>1,010</td>
        <td>massa</td>
        <td>Vestibulum</td>
        <td>lacinia</td>
        <td>arcu</td>
      </tr>
      <tr>
        <td>1,011</td>
        <td>eget</td>
        <td>nulla</td>
        <td>Class</td>
        <td>aptent</td>
      </tr>
      <tr>
        <td>1,012</td>
        <td>taciti</td>
        <td>sociosqu</td>
        <td>ad</td>
        <td>litora</td>
      </tr>
      <tr>
        <td>1,013</td>
        <td>torquent</td>
        <td>per</td>
        <td>conubia</td>
        <td>nostra</td>
      </tr>
      <tr>
        <td>1,014</td>
        <td>per</td>
        <td>inceptos</td>
        <td>himenaeos</td>
        <td>Curabitur</td>
      </tr>
      <tr>
        <td>1,015</td>
        <td>sodales</td>
        <td>ligula</td>
        <td>in</td>
        <td>libero</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

{% block javascripts %}
<script src="{% static 'assets/js/chart.min.js' %}"></script>
<script>
  (function() {
    'use strict'
    // Graphs
    var ctx = document.getElementById('myChart')
    // eslint-disable-next-line no-unused-vars
    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: [
          'Sunday',
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday'
        ],
        datasets: [{
          data: [
            15339,
            21345,
            18483,
            24003,
            23489,
            24092,
            12034
          ],
          lineTension: 0,
          backgroundColor: 'transparent',
          borderColor: '#007bff',
          borderWidth: 4,
          pointBackgroundColor: '#007bff'
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: false
            }
          }]
        },
        legend: {
          display: false
        }
      }
    })
  })()
</script>
{% endblock javascripts %}

dashboard/templates/dashboard/pages/profile.html
{% extends "../layouts/base.html" %}
{% load static %}

{% block title %} Profile {% endblock %}

{% block page_tools %}
<a role="button" class="btn btn-sm btn-outline-secondary mr-2" href="{% url 'dash:profile_edit' %}">Edit</a>
<div class="btn-group">
  <a role="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#DiableModalLabel">Disable</a>
  <a role="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#DeleteModalLabel">Delete</a>
</div>
{% endblock %}

{% block content %}
<section class="section about-section gray-bg" id="about">
    <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6">
              <div class="about-avatar text-center">
                  <img class="shadow-sm p-1 bg-white border rounded-circle" src="{% if user.picture %}{{ user.picture.url }}{% else %}{% static 'assets/img/profile-picture.png' %}{% endif %}" width="200" height="200">
              </div>
          </div>
            <div class="col-lg-6">
              <h6 class="theme-color lead">{% if user.first_name or user.last_name %}{{ user.first_name|title }} {{ user.last_name|title }}  (@{{ user.username }}){% else %}{{ user.username }}{% endif %}{% if user.is_staff %}<small class="ml-2"><span class="badge badge-pill badge-success">staff</span></small>{% endif %}</h6>
              <p>{{ user.bio }}</p>
              <div class="row about-list">
                  <div class="col-md-6">
                      <div class="media">
                          <label>Birthday</label>
                          <p>{{ user.birthday }}</p>
                      </div>
                      <div class="media">
                          <label>Joined on</label>
                          <p>{{ user.date_joined }}</p>
                      </div>
                  </div>
                  <div class="col-md-6">
                      <div class="media">
                          <label>E-mail</label>
                          <p>{{ user.email }}</p>
                      </div>
                      <div class="media">
                          <label>Last login</label>
                          <p>{{ user.last_login }}</p>
                      </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
</section>

<!-- DISABLE DIALOG BOX -->
<div class="modal fade" id="DiableModalLabel" tabindex="-1" aria-labelledby="DiableModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Disable your account?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>You are about to diable your account and you will not be able to login back. Do you wish to continue?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a role="button" class="btn btn-danger" href="{% url 'auth:disable' username=user.username %}">Disable</a>
      </div>
    </div>
  </div>
</div>

<!-- DELETE DIALOG BOX -->
<div class="modal fade" id="DeleteModalLabel" tabindex="-1" aria-labelledby="DeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Delete your account?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>You are about to delete your account and you will not be able to login back. Do you wish to continue?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a role="button" class="btn btn-danger" href="{% url 'auth:delete' username=user.username %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

dashboard/templates/dashboard/pages/profile_edit.html
{% extends "../layouts/base.html" %}
{% load crispy_forms_tags %}

{% block title %} Edit Profile {% endblock %}

{% block page_tools %}
<a role="button" class="btn btn-sm btn-outline-secondary" href="{% url 'dash:profile' %}">Back</a>
{% endblock %}

{% block content %}
<form class="form-signup form-group" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-primary my-3" type="submit">Save</button>
</form>
{% endblock %}

dashboard/templates/dashboard/pages/users.html
{% extends "../layouts/base.html" %}
{% load static %}

{% block title %} Users {% endblock %}

{% block page_tools %}
<a role="button" class="btn btn-sm btn-outline-secondary mr-2" href="{% url 'dash:profile_edit' %}">Edit</a>
{% endblock %}

{% block content %}
  {% if users and user.is_staff %}
  <div class="table-responsive mt-5">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Username</th>
          <th scope="col">Email Verification</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>@{{ user.username }}</td>
          <td>{% if not user.email_verified %}
            <a class="btn btn-success btn-sm mb-1" href="{% url 'auth:verify_email' username=user.username token=user.hashed %}" role="button">Verify</a>
          {% else %}
            <p>Verified</p>
          {% endif %}</td>
          <td>{% if user.is_active %}Active{% else %}Inctive{% endif %}</td>
          <td>
            <a class="btn btn-warning btn-sm mb-1" href="{% url 'auth:force_logout' username=user.username %}" role="button">Force Logout</a>
            {% if not user.is_active %}
              <a class="btn btn-success btn-sm mb-1" href="{% url 'auth:enable' username=user.username %}" role="button">Enable</a>
            {% else %}
              <a class="btn btn-danger btn-sm mb-1" href="{% url 'auth:disable' username=user.username %}" role="button">Disable</a>
            {% endif %}
            <a class="btn btn-danger btn-sm mb-1" href="{% url 'auth:delete' username=user.username %}" role="button">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <p class="text-muted">No inactive users found</p>
  {% endif %}
{% endblock %}