accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'auth'
urlpatterns = [
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('force_logout/<username>', views.user_force_logout, name='force_logout'),
    path('enable/<username>', views.user_enable, name='enable'),
    path('disable/<username>', views.user_disable, name='disable'),
    path('delete/<username>', views.user_delete, name='delete'),
    path('verify/<username>/<token>', views.user_verify_email, name='verify_email'),
    path('gmail/', include('gmailer.urls')),
]

config/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('dashboard/', include('dashboard.urls', namespace='dash')),
    path('auth/', include('accounts.urls', namespace='auth')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.errors.page_not_found'
handler500 = 'core.errors.server_error'
handler403 = 'core.errors.permission_denied'
handler400 = 'core.errors.bad_request'

core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name="home"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'core/home.html')

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  {% include 'common/head.html' %}

  <title>{% block title %}Django Dash{% endblock %}</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/cover/">

  {% include 'common/styles.html' %}
  <link href="{% static 'assets/css/home.css' %}" rel="stylesheet">
</head>

<body class="text-center">
  {% include 'common/messages.html' %}

  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
      <div class="inner">
        <a href="{% url 'core:home' %}"><h3 class="masthead-brand">Django Dash</h3></a>
        <nav class="nav nav-masthead justify-content-center">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'dash:home' %}">Dashboard</a>
          <a class="nav-link" href="{% url 'auth:logout' %}?next=/">Sign Out</a>
          {% else %}
          <a class="nav-link" href="{% url 'auth:login' %}?next=/">Sign In</a>
          <a class="nav-link" href="{% url 'auth:signup' %}?next=/">Sign Up</a>
          {% endif %}
        </nav>
      </div>
    </header>

    {% block content %}{% endblock %}

    <footer class="mastfoot mt-auto">
      <div class="inner">
        <p>Django Auth using <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://github.com/nikhiljohn10">@nikzjon</a>.</p>
      </div>
    </footer>
  </div>
  {% include 'common/scripts.html' %}
  <script type="text/javascript">
    $('html').addClass('d-none');
    $(document).ready(function() {
      $('html').removeClass('d-none');
    });
  </script>
</body>

</html>

core/templates/core/home.html
{% extends './base.html' %}
{% block content %}
<main role="main" class="inner cover">
  <h1 class="cover-heading">Django Dash</h1>
  {% if user.is_authenticated %}
  <p class="lead">Welcome, {{ user.username }}</p>
  {% else %}
  <p class="lead">Django authentication example</p>
  {% endif %}
  <p class="lead pt-5">
    <a href="https://github.com/nikhiljohn10/django-auth" class="btn btn-lg btn-secondary">Source Code</a><br>
  </p>
</main>
{% endblock %}