accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'auth'
urlpatterns = [
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('force_logout/<username>', views.user_force_logout, name='force_logout'),
    path('enable/<username>', views.user_enable, name='enable'),
    path('disable/<username>', views.user_disable, name='disable'),
    path('delete/<username>', views.user_delete, name='delete'),
    path('verify/<username>/<token>', views.user_verify_email, name='verify_email'),
    path('gmail/', include('gmailer.urls')),
]

core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name="home"),
]

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dash'
urlpatterns = [
    path('', views.home, name="home"),
    path('users/', views.users, name='users'),
    path('gmail/', views.gmail, name='gmail'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

dashboard/models.py
from django.db import models

dashboard/forms.py
from accounts.models import User
from django import forms

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'bio', 'birthday', 'picture']
        widgets = {
            'picture': forms.ClearableFileInput(attrs={ 'class': 'form-control mb-3', 'placeholder': 'Profile Picture'}),
        }

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from dashboard.forms import ProfileForm
from accounts.models import User
from accounts.tools import activater


@login_required
def home(request):
    return render(request, 'dashboard/pages/home.html')


@login_required
def profile(request):
    return render(request, 'dashboard/pages/profile.html')


@login_required
@permission_required("is_staff", login_url='/dashboard/')
def users(request):
    users = User.objects.filter(is_staff=False)
    for user in users:
        if not user.email_verified:
            user.hashed = activater.make_token(user)
        else:
            user.hashed = "Verified"
    return render(request, 'dashboard/pages/users.html', {'users': users})


@login_required
@permission_required("is_staff", login_url='/dashboard/')
def gmail(request):
    credentials = None
    # if mailer.activated:
    #     credentials = mailer.credentials
    #     credentials.email = mailer.email
    return render(request, 'dashboard/pages/gmail.html', {'credentials': credentials})


class ProfileEditView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'dashboard/pages/profile_edit.html'
    success_url = '/dashboard/profile'
    form_class = ProfileForm

    def get_object(self, *args, **kwargs):
        return get_object_or_404(User, pk=self.request.user.pk)


profile_edit = ProfileEditView.as_view()

dashboard/templates/dashboard/common/navigation.html
<!-- Static assets -->
{% load static %}
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{% url 'core:home' %}">Django Dash</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'auth:logout' %}">Sign out</a>
    </li>
  </ul>
</nav>

dashboard/templates/dashboard/common/sidebar-item.html
<li class="nav-item">
  <a class="nav-link {% if request.path == url %}active{% endif %}" href="{{ url }}">
    <span data-feather="{{ icon }}"></span>
    {{ name }} {% if request.path == url %}<span class="sr-only">(current)</span>{% endif %}
  </a>
</li>

dashboard/templates/dashboard/common/sidebar.html
{% load thumbnail %}
{% load static %}
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="sidebar-sticky pt-3">
    <div class="text-center">
      <h5 class="h5 mb-3">
        {% if user.picture %}
            {% thumbnail user.picture "100x100" crop="center" as img %}
            <img class="shadow-sm p-1 bg-white border rounded-circle" src="{{ img.url }}" width="{{ img.width }}" height="{{ img.height }}">
            {% empty %}
            <img class="shadow-sm p-1 bg-white border rounded-circle" src="{{ user.picture.url }}" width="100" height="100">
            {% endthumbnail %}
          {% else %}
          <img class="shadow-sm p-1 bg-white border rounded-circle" src="{% static 'assets/img/profile-picture.png' %}" width="100" height="100">
        {% endif %}
      </h5>
      <h5 class="h5 mb-3">
        <span>Welcome, {% if user.first_name %}Mr.{{ user.first_name }}{% else %}{{ user.username }}{% endif %}</span>
      </h5>
    </div>
    <hr>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <div class="d-flex align-items-center text-muted">
        <span data-feather="home" class="mr-2"></span>Home
      </div>
    </h6>
    <ul class="nav flex-column mb-2 ml-4">

      {% url 'dash:home' as url %}
      {% include 'dashboard/common/sidebar-item.html' with name='Dashboard' icon='monitor' %}

      {% url 'dash:profile' as url %}
      {% include 'dashboard/common/sidebar-item.html' with name='Profile' icon='user' %}

    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <div class="d-flex align-items-center text-muted">
        <span data-feather="settings" class="mr-2"></span>Settings
      </div>
    </h6>
    <ul class="nav flex-column mb-2 ml-4">

      {% if user.is_staff %}

        {% url 'dash:users' as url %}
        {% include 'dashboard/common/sidebar-item.html' with name='Users' icon='users' %}

        {% url 'dash:gmail' as url %}
        {% include 'dashboard/common/sidebar-item.html' with name='Gmail' icon='mail' %}

      {% endif %}

    </ul>
  </div>
</nav>